### ISSUE TITLE
训练中遇到的问题

### ISSUE THREAD

**Issue by chenqj97** [ohhhyeahhh/SiamGAT#20]
RuntimeError: CUDA out of memory. Tried to allocate 182.00 MiB (GPU 0; 11.00 GiB total capacity; 9.38 GiB already allocated; 37.75 MiB free; 174.94 MiB cached)
作者您好，这是我再训练中遇到的问题，我的设备是一块1080Ti,遇到第11个epoch时候，总是会报这个错误，请问一下怎么解决，前面10个epoch都好好的，总是在这里报错，明明显存还挺大的阿，论文说是在4个2080Ti上跑，是否要更改是什么代码，很急，希望早日收到回复，感谢

**Comment by WangJun-ZJUT** [comment]
你好，这个问题是由于显存不够导致的，前10轮训练过程中，backbone的参数是冻结的，所以不会大量占用显存，在后10轮的训练中需要加入backbone的参数一起finetune，所以会出现显存不足的情况。通常可以通过降低batch size来解决，你可以在训练开始前将start epoch设置为11检查是否会超出显存，确认可以正常训练后再从第0轮开始训练。

**Comment by chenqj97** [comment]
好的，已经解决，十分感谢

**Comment by chenqj97** [comment]
还有个问题，就是自己训练完后，怎么得到论文提到的精度和成功率？是eval吗
